# Site settings
title: Marie Azcueta
email: marieazc@gmail.com
description: "Graphic Designer > Product Designer > Visual Designer at Bloomberg UX "
baseurl: " "
url: "http://marieazcueta.com"

# Build settings
markdown: kramdown
permalink: none
exclude: [Gemfile*, vendor/]
category-list: ['dashboard', 'styleguide', 'apps', 'design']
